"""empty message

Revision ID: 656d7af530de
Revises: 
Create Date: 2024-06-12 16:37:12.064327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656d7af530de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artigo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('codigoArtigo', sa.String(length=21), nullable=False),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigoArtigo'),
    sa.UniqueConstraint('descricao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artigo')
    # ### end Alembic commands ###
